#!/usr/bin/env python3
"""
Visualize Lorenz system simulation results from VCD file.

This script:
1. Parses the VCD file generated by the simulation
2. Converts Q7.20 fixed-point values to floating-point
3. Plots x, y, z vs time
4. Plots 3D trajectory
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
import sys
import os
import re

# Q7.20 fixed-point conversion: 7 integer bits, 20 fractional bits, signed
# Format: signed 27-bit = 1 sign bit + 6 integer bits + 20 fractional bits
# To convert: value / (2^20)
FIXED_POINT_SCALE = 2.0 ** 20


def q720_to_float(value_int):
    """Convert Q7.20 fixed-point integer to floating-point."""
    # Handle two's complement for negative numbers
    if value_int >= (1 << 26):
        value_int = value_int - (1 << 27)
    return value_int / FIXED_POINT_SCALE


def parse_vcd_simple(vcd_file, signal_names):
    """
    Simple VCD parser to extract signal values over time.
    Returns: {signal_name: [(time, value), ...]}
    """
    signals = {name: [] for name in signal_names}
    signal_vars = {}  # Map VCD variable code to signal name
    current_values = {}  # Current value for each signal
    
    current_time = 0
    
    with open(vcd_file, 'r') as f:
        content = f.read()
    
    lines = content.split('\n')
    
    # First pass: find signal variable declarations
    in_scope = False
    for line in lines:
        line_stripped = line.strip()
        if '$scope' in line_stripped and 'testbench' in line_stripped:
            in_scope = True
            continue
        if line_stripped.startswith('$upscope'):
            in_scope = False
            continue
        if in_scope:
            # Look for variable declarations: $var wire 27 var_code x_out $end
            var_match = re.search(r'\$var\s+wire\s+(\d+)\s+(\S+)\s+(\w+)\s+\$end', line_stripped)
            if var_match:
                width, var_code, var_name = var_match.groups()
                if var_name in signal_names:
                    signal_vars[var_code] = var_name
                    current_values[var_code] = None
                    print(f"Found signal: {var_name} -> {var_code} (width={width})")
    
    if not signal_vars:
        print("Warning: No signals found. Trying alternate parsing...")
        # Try simpler pattern
        for line in lines:
            var_match = re.search(r'\$var.*?(\S+)\s+(x_out|y_out|z_out)', line)
            if var_match:
                var_code = var_match.group(1)
                var_name = var_match.group(2)
                signal_vars[var_code] = var_name
                current_values[var_code] = None
                print(f"Found signal (alt): {var_name} -> {var_code}")
    
    print(f"Parsing VCD with {len(signal_vars)} signals...")
    
    # Second pass: parse value changes
    for line in lines:
        line_stripped = line.strip()
        if not line_stripped:
            continue
        
        # Time change: #timestamp
        if line_stripped.startswith('#'):
            # Save current values at this time point
            for var_code, signal_name in signal_vars.items():
                if current_values[var_code] is not None:
                    signals[signal_name].append((current_time, current_values[var_code]))
            
            try:
                current_time = int(line_stripped[1:])
            except ValueError:
                continue
            continue
        
        # Skip directive lines
        if line_stripped.startswith('$'):
            continue
        
        # Value changes: try different formats
        for var_code, signal_name in signal_vars.items():
            value_float = None
            
            # Format 1: Binary - b[01]+ var_code
            binary_match = re.match(r'b([01]+)\s+' + re.escape(var_code) + r'\s*$', line_stripped)
            if binary_match:
                bin_str = binary_match.group(1)
                # Pad to 27 bits with ZERO-extend (VCD omits leading zeros)
                # The two's complement conversion below handles the sign
                if len(bin_str) < 27:
                    bin_str = '0' * (27 - len(bin_str)) + bin_str
                if len(bin_str) >= 27:
                    value_int = int(bin_str[:27], 2)
                    # Handle two's complement for negative numbers
                    if value_int >= (1 << 26):
                        value_int = value_int - (1 << 27)
                    value_float = q720_to_float(value_int)
            
            # Format 2: Hex - h[0-9a-fA-F]+ var_code  
            if value_float is None:
                hex_match = re.match(r'h([0-9a-fA-F]+)\s+' + re.escape(var_code) + r'\s*$', line_stripped)
                if hex_match:
                    hex_str = hex_match.group(1)
                    value_int = int(hex_str, 16)
                    # Mask to 27 bits
                    value_int = value_int & ((1 << 27) - 1)
                    # Handle two's complement
                    if value_int >= (1 << 26):
                        value_int = value_int - (1 << 27)
                    value_float = q720_to_float(value_int)
            
            # Format 3: Simple value var_code (for single bits, but might work)
            if value_float is None:
                simple_match = re.match(r'([01xXzZ])\s*' + re.escape(var_code) + r'\s*$', line_stripped)
                if simple_match:
                    # Skip if not valid
                    pass
            
            if value_float is not None:
                current_values[var_code] = value_float
                break
    
    # Final save
    for var_code, signal_name in signal_vars.items():
        if current_values[var_code] is not None:
            signals[signal_name].append((current_time, current_values[var_code]))
    
    return signals


def parse_vcd_pyvcd(vcd_file, signal_names):
    """Parse VCD using pyvcd library if available."""
    try:
        from vcd import VCDParser
        
        parser = VCDParser()
        with open(vcd_file, 'r') as f:
            signals = {name: [] for name in signal_names}
            
            for timestamp, signal_changes in parser.parse(f):
                for var, value in signal_changes:
                    var_name = var.references[0] if var.references else None
                    if var_name in signal_names:
                        # Convert to float
                        if isinstance(value, int):
                            value_float = q720_to_float(value)
                        else:
                            value_float = q720_to_float(int(value))
                        signals[var_name].append((timestamp, value_float))
            
            return signals
    except ImportError:
        print("pyvcd not available, using simple parser")
        return None




def main():
    # Default VCD file
    vcd_file = 'build/testbench.vcd'
    
    if len(sys.argv) > 1:
        vcd_file = sys.argv[1]
    
    if not os.path.exists(vcd_file):
        print(f"Error: VCD file '{vcd_file}' not found!")
        print("Run 'make run' first to generate the VCD file.")
        sys.exit(1)
    
    print(f"Parsing VCD file: {vcd_file}")
    
    # Try pyvcd first, fall back to simple parser
    signal_names = ['x_out', 'y_out', 'z_out']
    signals = parse_vcd_pyvcd(vcd_file, signal_names)
    
    if signals is None:
        signals = parse_vcd_simple(vcd_file, signal_names)
    
    # Extract time series
    # Filter to only get values when reset is released (after initialization)
    x_data = signals['x_out']
    y_data = signals['y_out']
    z_data = signals['z_out']
    
    # Convert to numpy arrays, skipping reset period
    # Find where reset is released (values start changing significantly)
    if len(x_data) > 100:
        # Skip first 100 points (reset period)
        start_idx = min(100, len(x_data) // 10)
    else:
        start_idx = 0
    
    times = np.array([t for t, _ in x_data[start_idx:]]) / 1e9  # Convert ns to seconds
    x_sim = np.array([v for _, v in x_data[start_idx:]])
    y_sim = np.array([v for _, v in y_data[start_idx:]])
    z_sim = np.array([v for _, v in z_data[start_idx:]])
    
    print(f"Loaded {len(x_sim)} data points")
    print(f"Time range: {times[0]:.6f} to {times[-1]:.6f} seconds")
    print(f"X range: {x_sim.min():.3f} to {x_sim.max():.3f}")
    print(f"Y range: {y_sim.min():.3f} to {y_sim.max():.3f}")
    print(f"Z range: {z_sim.min():.3f} to {z_sim.max():.3f}")
    
    # Plot 1: 3D Trajectory
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection='3d')
    ax.plot(x_sim, y_sim, z_sim, linewidth=0.6)
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('z')
    ax.set_title('Lorenz System Trajectory (Verilog Simulation)')
    plt.tight_layout()
    plt.savefig('build/lorenz_3d_trajectory.png', dpi=150)
    print("Saved: lorenz_3d_trajectory.png")
    
    # Plot 2: Time series for x, y, z
    fig, axes = plt.subplots(3, 1, figsize=(12, 8))
    
    axes[0].plot(times, x_sim, linewidth=0.8)
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('x(t)')
    axes[0].set_title('x vs time')
    axes[0].grid(True, alpha=0.3)
    
    axes[1].plot(times, y_sim, linewidth=0.8)
    axes[1].set_xlabel('Time (s)')
    axes[1].set_ylabel('y(t)')
    axes[1].set_title('y vs time')
    axes[1].grid(True, alpha=0.3)
    
    axes[2].plot(times, z_sim, linewidth=0.8)
    axes[2].set_xlabel('Time (s)')
    axes[2].set_ylabel('z(t)')
    axes[2].set_title('z vs time')
    axes[2].grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('build/lorenz_time_series.png', dpi=150)
    print("Saved: lorenz_time_series.png")
    
    # Check if simulation is maintaining oscillations
    print("\n=== Simulation Statistics ===")
    x_range = x_sim.max() - x_sim.min()
    y_range = y_sim.max() - y_sim.min()
    z_range = z_sim.max() - z_sim.min()
    
    print(f"X amplitude range: {x_range:.3f}")
    print(f"Y amplitude range: {y_range:.3f}")
    print(f"Z amplitude range: {z_range:.3f}")
    
    if x_range < 0.1:
        print("WARNING: X values appear to have converged/died out!")
    if y_range < 0.1:
        print("WARNING: Y values appear to have converged/died out!")
    if z_range < 0.1:
        print("WARNING: Z values appear to have converged/died out!")
    
    print("\nShowing plots...")
    plt.show()


if __name__ == '__main__':
    main()