# TCL File Generated by Component Editor 18.1
# Thu Apr 30 20:50:54 EDT 2026
# DO NOT MODIFY


# 
# mcmc_system "do_not_use" v1.0
#  2026.04.30.20:50:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mcmc_system
# 
set_module_property DESCRIPTION ""
set_module_property NAME mcmc_system
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME do_not_use
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file mcmc_system.v VERILOG PATH mcmc_system.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter NUM_CORES INTEGER 4
set_parameter_property NUM_CORES DEFAULT_VALUE 4
set_parameter_property NUM_CORES DISPLAY_NAME NUM_CORES
set_parameter_property NUM_CORES TYPE INTEGER
set_parameter_property NUM_CORES UNITS None
set_parameter_property NUM_CORES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_CORES AFFECTS_GENERATION false
set_parameter_property NUM_CORES HDL_PARAMETER true
add_parameter MAX_NODES INTEGER 32
set_parameter_property MAX_NODES DEFAULT_VALUE 32
set_parameter_property MAX_NODES DISPLAY_NAME MAX_NODES
set_parameter_property MAX_NODES TYPE INTEGER
set_parameter_property MAX_NODES UNITS None
set_parameter_property MAX_NODES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_NODES AFFECTS_GENERATION false
set_parameter_property MAX_NODES HDL_PARAMETER true
add_parameter MAX_CANDS INTEGER 64
set_parameter_property MAX_CANDS DEFAULT_VALUE 64
set_parameter_property MAX_CANDS DISPLAY_NAME MAX_CANDS
set_parameter_property MAX_CANDS TYPE INTEGER
set_parameter_property MAX_CANDS UNITS None
set_parameter_property MAX_CANDS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_CANDS AFFECTS_GENERATION false
set_parameter_property MAX_CANDS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point mcmc_control
# 
add_interface mcmc_control conduit end
set_interface_property mcmc_control associatedClock clock
set_interface_property mcmc_control associatedReset ""
set_interface_property mcmc_control ENABLED true
set_interface_property mcmc_control EXPORT_OF ""
set_interface_property mcmc_control PORT_NAME_MAP ""
set_interface_property mcmc_control CMSIS_SVD_VARIABLES ""
set_interface_property mcmc_control SVD_ADDRESS_GROUP ""

add_interface_port mcmc_control active_nodes export Input 32


# 
# connection point avalon_slave_0_1
# 
add_interface avalon_slave_0_1 avalon end
set_interface_property avalon_slave_0_1 addressUnits WORDS
set_interface_property avalon_slave_0_1 associatedClock clock
set_interface_property avalon_slave_0_1 associatedReset reset
set_interface_property avalon_slave_0_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1 holdTime 0
set_interface_property avalon_slave_0_1 linewrapBursts false
set_interface_property avalon_slave_0_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1 readLatency 0
set_interface_property avalon_slave_0_1 readWaitTime 1
set_interface_property avalon_slave_0_1 setupTime 0
set_interface_property avalon_slave_0_1 timingUnits Cycles
set_interface_property avalon_slave_0_1 writeWaitTime 0
set_interface_property avalon_slave_0_1 ENABLED true
set_interface_property avalon_slave_0_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1 avs_address address Input 11
add_interface_port avalon_slave_0_1 avs_write write Input 1
add_interface_port avalon_slave_0_1 avs_writedata writedata Input 64
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isPrintableDevice 0

